app/src/processing/app/Base.java, app/src/processing/app/Recent.java, app/src/processing/app/Sketch.java
Open Recent list is now updated when renaming within processing.  
Closes #2984.
=> Open Recent files now dislays sketch after rename

build/shared/lib/languages/PDE_fr.properties
Set of commits adding several french translations. There are, however, several translations yet to be completed, most notably several menu options in the debug menu.
=> Added several French translations

core/src/processing/core/PShape.java
=> rectMode getting called with correct argument now.

core/src/processing/core/PApplet.java
=> use default colorMode() with lerpColor() outside setup()

app/src/processing/app/contrib/ContributionManager.java, app/src/processing/app/contrib/ContributionManagerDialog.java, app/src/processing/app/contrib/ProgressMonitor.java
This doesn't create a progress bar but it does display the download percentage along with the status. This is an alternative implementation for #3160.
`Downloading... (56%)`.
I apologize for all the "random" line changes in my commit. My IDE automatically cleaned up a bunch of lines that had extra tabs and spaces on them.
=> Display download percentage when fetching library info

app/src/processing/app/contrib/ContributionListing.java
This fix resolves #3168. Again, sorry about that.
=> Contribution Manager up and running again

app/src/processing/app/syntax/InputHandler.java
Fix for Exception when pressing PgDn in a code without scrollbar #2990
=> Fix for Exception when pressing PgDn in a code without scrollbar #2990

app/src/processing/app/Recent.java, core/src/processing/core/PApplet.java, core/src/processing/core/PShapeOBJ.java
PR for a commit that closes a few BufferedReaders and InputStreams
=> Closing a few unclosed BufferedReaders and InputStreams

java/src/processing/mode/java/pdex/JavaTextAreaPainter.java
Signed-off-by: Umair Khan <omerjerk@gmail.com>
I think hovering on the error should display the error. Just as in eclipse/idea.
=> Show tooltip on hovering over the error

build/shared/lib/languages/PDE_de.properties, build/shared/lib/languages/PDE_es.properties
All strings all translated now.
=> Improve spanish localization

app/src/processing/app/syntax/JEditTextArea.java
Fix for #3148 
Though this fixes the current issue there is a lot of  buggy areas in horizontal offset .
It would be nice if the author can document these function in detail so that they can be made bug free.
=> Now the cursor moves when the line is changed after a long line

app/src/processing/app/PreferencesFrame.java
Fix for #67 
This is very similar to the current Preference Window.
The old code has not been cleaned, i will do it once design is finalized ( and also add comments ). 
Some suggestion i think should be done are 
* Size of Ok and Cancel should be increased
* Window should be made resizable
* "Background color when Presenting" should be changed to something more meaningful
=> Initial Stage for Preference Window with GroupLayout

app/src/processing/app/FindReplace.java
The old code has not been cleaned yet and there is also no documentation, i will do these once the design is agreed upon.  
This produces a dialog similar to the already present one but some changes that could be made are 
* Enclose the checkboxes in a border under Options heading
* Move 2 buttons to the next line
* Make sizes of all the buttons equal
=> Find/Replace dialog uses GroupLayout

core/src/processing/core/PShapeSVG.java
Proper support for percentages, partial support for viewbox, full
support for named colors, allow gradients to specify color-stops using
style or direct attributes on &lt;stop&gt; (fix #2992), nicer error message on loading an
HTML document as SVG (since I assume it can happen to novices
downloading SVGs from the web).
~~Also unrelated edit to PApplet which disabled a doc comment which was
coming up in the wrong place.~~
=> Improvements to SVG. Fixes #2992.

app/src/processing/app/FindReplace.java
=> Find/Replace Window now looks like original.

app/src/processing/app/PreferencesFrame.java
=> Restored the nonResizable nature of Font Size Field in Pref Window.

build/shared/lib/languages/PDE_el.properties
This PR fixes #3329 and also adds some missing translations
=> fix Greek error messages

app/src/processing/app/contrib/ContributionManagerDialog.java
Wasn't sure if this would be accepted so made it a different PR
=> Made the vertical scrollbar to be displayed when needed

app/src/processing/app/Toolkit.java
Also made it get a bit closer to the style guide, and other tweaks.  Essentially, the problem is that `setMnemonic` ignores the case, so you have to manually instruct the API to underline the letter you asked for.
=> Fix case-related bugs in Toolkit::setMenuMnemonics

app/src/processing/app/Editor.java, app/src/processing/app/FindReplace.java, app/src/processing/app/Toolkit.java
Finishes #53. I've changed some of the old code for the sake of looping more easily and stuff. Also removed the joke about the treatment of poor quality programmers in "some countries", since those countries aren't all that funny.
=> Make some menu items inactive when unusable

app/src/processing/app/Mode.java, build/shared/lib/languages/PDE.properties
This resolves #3420 by adding back in an accidentally deleted method. After the fix, things now look like:
=> Examples window shows contributed examples

build/shared/lib/languages/PDE.properties, build/shared/tools/MovieMaker/src/processing/app/tools/MovieMaker.java
=> Internationalize MovieMaker.java.

app/src/processing/app/contrib/ContributionListPanel.java, app/src/processing/app/contrib/ContributionManagerDialog.java, app/src/processing/app/contrib/ContributionPanel.java, app/src/processing/app/contrib/ContributionTab.java, app/src/processing/app/contrib/StatusPanel.java
@benfry @alignedleft 
Things done
* The status bar is now up-to-date with the currently selected tab.
* There is a error popup kind of thing when net is not working with close and `Try Again` button.
* Fixed some bugs related to statusPanel not getting updated
Thing to do next
* Converting the list of contributions into table(working on that)
* Handle the special case of updateTab ( I am thinking about removing it from the tabbedPanel and making separate Pane for it otherwise the code will be filled with checks for the updatePanel).
=> CM with updated statusPanel and error popup

app/src/processing/app/contrib/ContributionListPanel.java, app/src/processing/app/contrib/ContributionManagerDialog.java, app/src/processing/app/contrib/ContributionTab.java, app/src/processing/app/contrib/StatusPanel.java
@alignedleft 
I thought it would be nice to do a PR before b11 is released
Things left to do
* Handle status tab (@benfry do you think i should make a separate layout for update panel or use many ifs to reuse the current one)
* Color-coding
* Ellipses in the contribution name. (@benfry can you please help me in this, see the line note)
* Remove threading(not needed any more)
* Fix that weird bug when python mode is selected from the list.
=> CM list converted into table

app/src/processing/app/contrib/ContributionListPanel.java, app/src/processing/app/contrib/ContributionListing.java, app/src/processing/app/contrib/ContributionTab.java, app/src/processing/app/contrib/StatusPanel.java
This should most probably fix #3464
=>  Added ellipses, improved error Panel, fixed a previous NPE bug

core/src/processing/core/PApplet.java, core/src/processing/opengl/PSurfaceJOGL.java
=> JOGL window size is now set properly

core/src/processing/opengl/PGraphicsOpenGL.java
Also moves vertex attribute collection to separate function.
=> Fix curves - properly this time

app/src/processing/app/contrib/AvailableContribution.java
=> imports added to mode

java/src/processing/mode/java/JavaBuild.java
=> Remove size() from setup() when copying to settings()

core/src/processing/core/PShape.java, core/src/processing/opengl/PShapeOpenGL.java
=> Fix setVertex for PATH PShapeOpenGL

build/shared/lib/languages/PDE_es.properties
I tried to stay close to the english texts, but some proved very difficult to localize. I replaced them with a less witty alternative.
We should also work on the writing style eventually, because I found lots of inconsistencies.
=> Update spanish translation

app/src/processing/app/Sketch.java
=> Rebuild tab menu on tab delete

app/src/processing/app/Sketch.java
Fixes #3099 
There is also a detailed explanation of what's going on.
=> Fix bug with tab sorting when adding new tabs

core/src/processing/opengl/PShapeOpenGL.java
Fixes null pointer exception in #3550
=> Fix null pointer exception in setVertex

app/src/processing/app/syntax/InputHandler.java
I implement auto complete about brackets and quotes. 
This support `()` , `{}` , `[]`, `""`, `''` .
=> Add auto-completion to brackets and quotes

core/src/processing/core/PImage.java
Let's blow the dust off these blending issues, shall we?
Fixed of-by-one error when blending onto itself
- related to #324
Reduced brightness fading in bilinear filtering
- fixes #258
Rewritten Java2D blend modes
- fixes #172
- fixes #514
=> Fix Java2D blending issues

app/src/processing/app/contrib/ContributionListPanel.java
=> Sorting by author name inplemented

app/src/processing/app/contrib/ContributionManagerDialog.java
=> Min size of CM is fixed

app/src/processing/app/contrib/StatusPanel.java
=> Deactivate install button when incompatible

app/src/processing/app/contrib/ContributionManagerDialog.java, app/src/processing/app/contrib/UpdateContributionTab.java
=> Update notification hidden when no update is there

app/src/processing/app/contrib/ContributionListing.java
=> Accented characters getting searched

app/src/processing/app/contrib/ContributionListPanel.java
=> Filter is working now

app/src/processing/app/contrib/ContributionListPanel.java
=> Arrow keys working in CM

java/src/processing/mode/java/preproc/PdeEmitter.java
- Map.Entry<String, Integer> is now possible
- java.util.List<Boolean> also possible
=> Preprocessor can now handle fully qualifies names

java/src/processing/mode/java/runner/Runner.java
=> Fix oversight in handleCommonErrors

app/src/processing/app/Mode.java, java/src/processing/mode/java/JavaMode.java, java/src/processing/mode/java/pdex/ASTGenerator.java
This will allow Android mode, or any other jar for that matter, to add android.jar to this searchable jars list.
Signed-off-by: Umair Khan <omerjerk@gmail.com>
=> Let the mode decide in which jars to search for during auto completion

core/src/processing/javafx/PSurfaceFX.java
- exclude decoration from sketch width/height
=> FX - Proper sketch sizing

app/src/processing/app/contrib/ContributionTab.java
=> Adding core libraries

app/src/processing/app/contrib/ContributionListPanel.java, app/src/processing/app/contrib/ContributionTab.java
=> Fixed width for category chooser

app/src/processing/app/contrib/ContributionManagerDialog.java, app/src/processing/app/contrib/ContributionTab.java, app/src/processing/app/contrib/UpdateContributionTab.java
Fix for #3599 
Please check for compatibility with mac.
=> Bar below the tab is painted

app/src/processing/app/contrib/StatusPanel.java
=> Fixed the size of the updateLabel

app/src/processing/app/contrib/ContributionTab.java
=> Visibility set for category chooser

app/src/processing/app/contrib/ContributionManagerDialog.java, app/src/processing/app/contrib/StatusPanel.java
=> Description is aligned with the names of contribution

core/src/processing/javafx/PSurfaceFX.java
Initialize FX only after the Application is launched.
Fixes #3690
=> FX - Initialize JavaFX properly

app/src/processing/app/contrib/ContributionListPanel.java, app/src/processing/app/contrib/ContributionManagerDialog.java, app/src/processing/app/contrib/StatusPanel.java
Fix for #3642 
@alignedleft 
The CM looks like this now.
=> Shifted the text right a little bit

app/src/processing/app/contrib/StatusPanel.java
=> No underline and no blue color

app/src/processing/app/contrib/UpdateContributionTab.java
=> Update buttom enabled when updates are present and background is set

app/src/processing/app/contrib/ContributionPanel.java, app/src/processing/app/contrib/StatusPanel.java
=> Label below install is visible now

app/src/processing/app/contrib/ContributionListPanel.java
=> Focus stays in the Filter Field while typing

app/src/processing/app/contrib/ContributionManagerDialog.java
=> Tab labels are not shifting up

core/src/processing/javafx/PGraphicsFX2D.java
Will be refactored later when I will have more complete picture of what should be happening inside the FX renderer and how to make it efficient. Density might not work correctly, that's also something I will be dealing with later.
=> FX - basic pixel operations (get, set, load, update)

app/src/processing/app/contrib/ContributionManagerDialog.java
=> Changed the order of tabs

core/src/processing/javafx/PSurfaceFX.java
- handle PRESSED and RELEASED for ".", "/", "*", "-", "+" and numeric keys
- prevent AIOOBE for all events
=> FX - improve key events

core/src/processing/opengl/PSurfaceJOGL.java
=> JOGL - normalize enter key

core/src/processing/core/PGraphics.java
=> Draw text with empty lines correctly

core/src/processing/awt/PGraphicsJava2D.java, core/src/processing/core/PApplet.java, core/src/processing/core/PGraphics.java, core/src/processing/javafx/PGraphicsFX2D.java, core/src/processing/opengl/PGraphicsOpenGL.java
- lookup for native FX fonts, font cache
- support for TTF, OTF and VLW
- tint cache for VLW fonts
- moved createFont into PGraphics
- cleaned up textFont and textSize in all renderers
=> FX - text stuff

java/src/processing/mode/java/MarkerColumn.java, java/src/processing/mode/java/pdex/LineMarker.java
=> Recalculate positions in error marker column on resize

core/src/processing/core/PGraphics.java
=> Fix PShape creation in P3D

app/src/processing/app/contrib/ContributionListing.java, app/src/processing/app/contrib/StatusPanel.java
=> Update to a incompatible version is not possible

app/src/processing/app/Base.java, app/src/processing/app/Mode.java, app/src/processing/app/ui/ExamplesFrame.java
=> Examples frame does not flikers when contribution is changed

app/src/processing/app/Base.java, app/src/processing/app/Mode.java, app/src/processing/app/ui/ExamplesFrame.java
Reverts processing/processing#3804
=> Revert "Examples frame does not flikers when contribution is changed"

app/src/processing/app/contrib/ContributionListing.java, app/src/processing/app/contrib/StatusPanel.java, app/src/processing/app/contrib/UpdateContributionTab.java
Fix for #3806 
I don't know why git isn't rebasing this.
=> Buttons disabled when clicked

app/src/processing/app/contrib/ContributionManagerDialog.java, app/src/processing/app/contrib/StatusPanel.java, app/src/processing/app/contrib/UpdateContributionTab.java
=> ContributionPanel are not getting duplicated in panelByContribution

java/src/processing/mode/java/JavaEditor.java, java/src/processing/mode/java/pdex/ASTGenerator.java, java/src/processing/mode/java/pdex/ASTNodeWrapper.java, java/src/processing/mode/java/pdex/CompletionPanel.java, java/src/processing/mode/java/pdex/ErrorCheckerService.java, java/src/processing/mode/java/pdex/JavaTextArea.java, java/src/processing/mode/java/pdex/JavaTextAreaPainter.java, java/src/processing/mode/java/pdex/SketchOutline.java
- fixed threading
- support for array types
- support for static access
- support for local classes
=> Code suggestions refactoring

core/src/processing/opengl/PGL.java, core/src/processing/opengl/PGraphicsOpenGL.java
- optimized native to Java color conversions
- optimized addVertex
=> Minor OpenGL improvements

java/src/processing/mode/java/JavaEditor.java, java/src/processing/mode/java/pdex/ErrorCheckerService.java, java/src/processing/mode/java/pdex/JavaTextAreaPainter.java
with handy tooltips
fixes #3759
=> Multiline wiggly underlines

java/src/processing/mode/java/pdex/XQPreprocessor.java
Typing "new color()" now results in error "class 'color' does not exists"
Fixes #3739
=> Remove color debug message

app/src/processing/app/ui/ErrorTable.java, java/src/processing/mode/java/JavaEditor.java, java/src/processing/mode/java/pdex/ASTGenerator.java, java/src/processing/mode/java/pdex/ErrorCheckerService.java, java/src/processing/mode/java/pdex/JavaTextArea.java
=> Small error checker and suggestions fixes

core/src/processing/opengl/FontTexture.java, core/src/processing/opengl/FrameBuffer.java, core/src/processing/opengl/PGraphicsOpenGL.java, core/src/processing/opengl/PShader.java, core/src/processing/opengl/PShapeOpenGL.java, core/src/processing/opengl/Texture.java
- keeps the good stuff in
- no side effects
- Dr. C. stamp of approval
=> Low-WeakReference diet

app/src/processing/app/contrib/ListPanel.java
=> Filter applied when refreshing

app/src/processing/app/contrib/ContribProgressBar.java, app/src/processing/app/contrib/ListPanel.java
Folow up on #3872
Runs on background thread, should be synchronized
=> Fix synchronization in ListPanel

app/src/processing/app/contrib/ContribProgressBar.java, app/src/processing/app/contrib/ContributionListing.java, app/src/processing/app/contrib/ContributionManager.java, app/src/processing/app/contrib/DetailPanel.java, app/src/processing/app/contrib/ListPanel.java, app/src/processing/app/contrib/LocalContribution.java, app/src/processing/app/contrib/UpdateListPanel.java
- UI is now updated on EDT. Should work for now, but needs more love
later, e.g. use SwingWorkers and update UI on EDT instead of
synchronizing everywhere.
- added TODOs about threading
Fixes #3882
=> CM - fix threading issues + threading notes

core/src/processing/awt/PSurfaceAWT.java
This is ugly, but I didn't find any other way.
Please test on Mac and Linux before merging.
Fixes #3868
=> Manage changing inset size when calling setResizable()

core/src/processing/opengl/PSurfaceJOGL.java
=> Fix fullScreen for OpenGL + Windows combo

app/src/processing/app/contrib/ContributionTab.java, app/src/processing/app/contrib/DetailPanel.java, app/src/processing/app/contrib/StatusPanel.java
=> CM - small fixes

app/src/processing/app/Base.java
=> Set update count on Editor startup

java/src/processing/mode/java/JavaEditor.java, java/src/processing/mode/java/pdex/ErrorCheckerService.java
- error checker toggle
- error checker listeners
=> Error checker update

app/src/processing/app/Sketch.java, app/src/processing/app/ui/ChangeDetector.java
=> Fix file counting in change detector

core/src/processing/core/PApplet.java
=> Fix welcome directory picker

java/src/processing/mode/java/pdex/ErrorCheckerService.java
=> Shutdown error checker executor properly

java/src/processing/mode/java/pdex/ASTGenerator.java, java/src/processing/mode/java/pdex/ErrorCheckerService.java
- Cleaned up Error Checker and AST Generator
- Libraries are now included
Fixes #3924
=> Library path for Error Checker and Suggestions

core/src/processing/opengl/PGraphicsOpenGL.java
Fix ordering when two triangles in a plane share vertices. Triangle still has to be tested with other triangles.
=> Depth sorter improvement

app/src/processing/app/Base.java
The message is set to null, not empty String
Fixes #3974
=> Fix NPE in Base

java/src/processing/mode/java/JavaMode.java
Was caused by a swing deadlock, resolved by using SwingUtilities.invokeLater 
issue: 
https://github.com/processing/processing/issues/3928
=> Fix for Tweak deadlock issue

build/shared/lib/languages/PDE_ja.properties
I will update more if I have a time, 
so don't merge this pull-request until next release(3.0.1) .
=> Update Japanese translation

build/linux/install-arm.sh
pi@raspberrypi ~ $ curl http://sukzessiv.net/~gohai/p5-arm/install-arm.sh | sudo sh
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  1588  100  1588    0     0   2121      0 --:--:-- --:--:-- --:--:--  2120
Downloading https://github.com/processing/processing/releases/download/processing-0247-3.0.1/processing-3.0.1-linux-armv6hf.tgz...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   610    0   610    0     0   1078      0 --:--:-- --:--:-- --:--:--  1081
100 87.8M  100 87.8M    0     0  4742k      0  0:00:18  0:00:18 --:--:-- 5414k
Installing in /usr/local...
Done! You can start processing by running "processing" in the terminal, …
=> Add installation script for ARM

app/src/processing/app/ui/FindReplace.java
=> Checked if the string to replace contains the string searched

core/src/processing/core/PApplet.java
=> Initialize sketch args before calling settings()

core/src/processing/core/PVector.java
Fix typo in docs. I don't know exactly how the documentation system works; will this update the website?
=> Fix typo in PVector.java docs

core/src/processing/core/PMatrix.java, core/src/processing/core/PMatrix2D.java, core/src/processing/core/PMatrix3D.java
I know that previously you've said that this is an advanced-users-only thing, but it would be nice to make it (reasonably) accessible.  I've ignored the actual translate/rotate/stretch etc. methods, since they're well documented in the normal web reference.
=> Flesh out the Javadoc for PMatrix.

java/src/processing/mode/java/Debugger.java, java/src/processing/mode/java/JavaEditor.java, java/src/processing/mode/java/JavaToolbar.java
- step button works correctly when SHIFT or ALT is pressed #4116
- fix NPE when stepping into static method #3590
- prevent NPE because ui was not updated on AWT
=> Debugger fixes

app/src/processing/app/syntax/Brackets.java, app/src/processing/app/syntax/JEditTextArea.java, java/src/processing/mode/java/MarkerColumn.java, java/src/processing/mode/java/pdex/JavaTextAreaPainter.java
Fixes to some index out of bounds exceptions I encountered in editor plus tooltip enhancements.
Fixes #3940
Might get rid of #3286
Fixes #1940
=> Various editor fixes

build/build.xml, build/jre/build.xml, build/macosx/appbundler/.settings/org.eclipse.jdt.core.prefs, build/shared/tools/MovieMaker/build.xml
Found some build files I missed.
=> Update app to Java 8 - leftovers

build/windows/config-cmd.xml, build/windows/config.xml
...so we can get rid of the workaround for JDK bug
=> Update min JRE version

app/src/processing/app/syntax/TextAreaPainter.java, java/src/processing/mode/java/pdex/JavaTextAreaPainter.java
=> Fix drawing lines with tabs

java/src/processing/mode/java/pdex/PreprocessingService.java
wait for running callbacks to finish before publishing new result
=> PPS: threading enhancement

java/src/processing/mode/java/JavaEditor.java, java/src/processing/mode/java/pdex/PDEX.java
Just a cleanup
Fixes #4281, go to declaration happens only when ctrl was pressed before the click
=> Move PDEX listeners from JavaEditor to PDEX

app/src/processing/app/Language.java, build/shared/lib/languages/PDE_uk.properties, build/shared/lib/languages/languages.txt
This is based on the v3.0.2 PDE.properties, so all the current strings should be translated.
_Note:_ Processing doesn't appear to have any obvious issues related to displaying cyrillic script.
=> Added Ukrainian localization

java/src/processing/mode/java/pdex/SourceUtils.java
=> PPS: Fix hex literals containing 'e' being suffixed by 'f'

app/src/processing/app/syntax/DefaultInputHandler.java, app/src/processing/app/syntax/InputHandler.java, app/src/processing/app/syntax/JEditTextArea.java, app/src/processing/app/syntax/TextAreaPainter.java
As discussed at #4326.
Closes #4250.
=> Remove partial support for rectangular selections.

java/src/processing/mode/java/JavaMode.java, java/src/processing/mode/java/pdex/PDEX.java
- polished ctrl/cmd+mouse1 interaction to make it less likely that it will be invoked by accident
- added preference to disable ctrl/cmd+mouse1 combo
Fixes #4466
=> Inspect mode polishing

app/src/processing/app/ui/Editor.java
Otherwise Save won't save the changes, because it saves only modified tabs.
Also runs compound edit timer tak on EDT.
=> Make undo/redo mark all affected tabs as modified

app/src/processing/app/ui/PreferencesFrame.java, java/src/processing/mode/java/JavaMode.java, java/src/processing/mode/java/pdex/PDEX.java
- Show Warnings now gets greyed out if check is not enabled
Fixes #4485
=> Return of the error check toggle

core/src/processing/core/PApplet.java
=> Give helpful message when createFont() called before setup()

java/src/processing/mode/java/pdex/PreprocessingService.java, java/src/processing/mode/java/pdex/SourceUtils.java
=> Error checker now adds 'public' to all default access methods

core/src/processing/core/PApplet.java
=> Changed the error message in JSON functions

build/shared/lib/languages/PDE_zh.properties
Completed most strings. Since the property file bundle is not synced, here still might be some missing things.
=> Chinese translation

build/macosx/language_gen.py
Hi there,
I made the shebang for the python interpreter more flexible. This helps running processing on FreeBSD / PCBSD without impacting any current user.
Cheers,
tpltnt
=> more flexible interpreter path

app/src/processing/app/contrib/ContributionListing.java, app/src/processing/app/contrib/ListPanel.java, app/src/processing/app/contrib/UpdateListPanel.java
=> Fixes the removal of redundant contribution and update related issues

java/src/processing/mode/java/pdex/SourceUtils.java
Same problem as with type constructors #4744
Fixes #4752
=> Fix hex color regex

app/src/processing/app/ui/ChangeDetector.java
=> Clean up ChangeDetector

core/src/processing/javafx/PGraphicsFX2D.java
As brought up by Jean Pierre Charalambos of Proscene fame.
=> FX: Reset transform to identity before drawing background

core/src/processing/javafx/PSurfaceFX.java
=> FX: Implement mouse wheel event

core/src/processing/javafx/PGraphicsFX2D.java
=> FX: Fix curveVertex drawing all curves together as one long curve

core/src/processing/javafx/PSurfaceFX.java
=> FX: Add exception handler which reports exceptions from user code

app/src/processing/app/ui/EditorButton.java, app/src/processing/app/ui/Toolkit.java
=> Enable bicubic interpolation for image-based editor components

java/src/processing/mode/java/Debugger.java, java/src/processing/mode/java/debug/LineBreakpoint.java
=> Fix breakpoints in inner classes

java/src/processing/mode/java/preproc/PdePreprocessor.java
=> Fix preproc skipping one char after a block comment

core/src/processing/awt/PGraphicsJava2D.java, core/src/processing/awt/PSurfaceAWT.java, core/src/processing/core/PApplet.java, core/src/processing/core/PGraphics.java, core/src/processing/javafx/PGraphicsFX2D.java, core/src/processing/javafx/PSurfaceFX.java, core/src/processing/opengl/PGraphicsOpenGL.java, core/src/processing/opengl/PSurfaceJOGL.java, java/src/processing/mode/java/runner/Runner.java
TODO:
- pixelDensity() needs JNA to do anything on Windows
- test/fix things on Linux
- implement Present mode for FX
- overhaul window-out-of-visible-area detection
=> Window placement and pixel density cleanup

core/src/processing/awt/PGraphicsJava2D.java, core/src/processing/javafx/PGraphicsFX2D.java
=> Fix typos made during pixelDensity update

app/src/processing/app/ui/ChangeDetector.java, app/src/processing/app/ui/Editor.java, java/src/processing/mode/java/JavaEditor.java, java/src/processing/mode/java/pdex/PreprocessingService.java
- Run Change Detector on EDT to prevent changes from user before finishing
- Notify Editor to run error check when Change Detector modifies the sketch
- Remove some unused code
Follow-up to #5021
=> Change Detector amendments

app/src/processing/app/ui/Editor.java
=> Fix comment/uncomment adding slashes at wrong indent

core/src/processing/opengl/PGL.java, core/src/processing/opengl/shaders/LineVert.glsl, core/src/processing/opengl/shaders/PointVert.glsl
Fixes #5181
Fixes #5182
Fixes #5183
Fixes #5194
point vert updated with the code from line vert to keep them in sync
=> Fix bugs in line vert shader

build/shared/tools/MovieMaker/src/processing/app/tools/MovieMaker.java
=> Unlock "Create Movie" in Movie Maker after use

java/src/processing/mode/java/pdex/SourceUtils.java
=> Fix scrub comments for empty block comment /**/

app/src/processing/app/Library.java, app/src/processing/app/ui/MarkerColumn.java, build/shared/tools/MovieMaker/src/ch/randelshofer/gui/datatransfer/FileTextFieldTransferHandler.java, core/src/processing/data/FloatDict.java, java/libraries/io/src/processing/io/LED.java, java/src/processing/mode/java/VariableInspector.java, java/src/processing/mode/java/debug/ArrayFieldNode.java, java/src/processing/mode/java/debug/LocalVariableNode.java, java/src/processing/mode/java/debug/VariableNode.java, java/src/processing/mode/java/tweak/SketchParser.java
- filter pattern 
- diamond operator
- multi-catch
=> Refactor to use a few Java 8 features

core/src/processing/opengl/shaders/LineVert.glsl
=> Fix line join triangles

java/libraries/net/src/processing/net/Client.java
Because I don't know how to count...
=> Fix Net library buffer sizes

java/src/processing/mode/java/Compiler.java
Comment said function throws RunnerException, but function throws SketchException which isn't related to RunnerException
=> Updated comment

build/shared/lib/languages/PDE_ru.properties, build/shared/lib/languages/languages.txt
I've added PDE_ru.properties and modified languages.txt. Is there anything else that i should do for integration of russian translation into Processing ?
=> Added Russian Translation

java/src/processing/mode/java/runner/Runner.java
=> Update java.lang.UnsupportedClassVersionError message

java/libraries/io/examples/SimpleInput/SimpleInput.pde
=> IO: Clarify SimpleInput example

build/build.xml
Steps to compile ld & windres:
```
sudo aptitude install mingw-w64
wget https://ftp.gnu.org/gnu/binutils/binutils-2.30.tar.bz2
tar vfx binutils-2.30.tar.bz2
cd binutils-2.30
./configure --target=i686-w64-mingw32
make -j4 -l4
sudo make install
```
=> Enable exporting of Windows applications on ARM (#5287)

java/libraries/io/examples/Servo_I2C_PCA9685/Servo_I2C_PCA9685.pde, java/libraries/io/src/processing/io/GPIO.java, java/libraries/io/src/processing/io/I2C.java
Great to see you back, @benfry!
The following is dealing with minor fallout from 3.3.7.1 - the only noteworthy change would be:
* IO: Make I2C errors more verbose
Best,
G
=> IO: Additional improvements

core/src/processing/core/PShape.java
Transformation matrix is now considered before checking for point inclusion. #1280
=> Finish implementation of PShape.contains()

app/src/processing/app/Language.java, build/shared/lib/languages/PDE_ru.properties
=> Updated russian translation, now can choose russian in preferences

build/shared/lib/languages/PDE_tr.properties
=>  turkish translation update

build/linux/appdata.xml
I am submitting the Processing app to Flathub [1] and there are a few improvements that are needed there for the appdata file.
It would also be awesome if you want to help out with maintenance of the flathub build manifest when new releases are made, since we encourage upstreams to publish apps directly.
Thanks for considering!
[1] https://github.com/flathub/flathub/pull/524
=> Improvements to the appdata file

core/src/processing/core/PApplet.java
=> Update missing @Deprecated tags in PApplet.java

build/shared/lib/languages/PDE_ru.properties
=> Minor changes for russian translation

app/src/processing/app/contrib/ContributionListing.java
=> Core libraries added to the count of updates

java/src/processing/mode/java/JavaEditor.java, java/src/processing/mode/java/JavaMode.java
Tweak mode was broken because RunnerListener could not be cast into JavaEditor anymore, so I added one more parameter giving tweakmode its editor back.
=> tweakmode fix for issue #5805

ISSUE_TEMPLATE.md
changes link to not rely on subdomain autoforwarding
=> update issue template -- correct forum link

build/shared/lib/languages/PDE_pt.properties
Guardr -> Guardar
Yah, não. -> Ah, não.
Nenhuns ficheiros ->  Nenhum dos ficheiros 
erro a descarregar -> erro ao descarregar
=> Small fixes for PDE_pt.properties

ISSUE_TEMPLATE.md
> STOP! PROCESSING 4 ISSUES GO TO https://github.com/processing/processing4/issues
=> Update ISSUE_TEMPLATE.md to redirect Processing 4 questions
