processing/processing

app/src/processing/app/contrib/ExamplesContribution.java

This PR resolves [#3037](https://github.com/processing/processing/issues/3037) by ensuring that the properties HashMap is not null, i.e., that the .properties file actually exists.

Missing examples.properties file no longer causes crash

---

app/src/processing/app/ChangeDetector.java

This PR moves all the GUI related operations to the main UI thread via EventQueue.invokeLater (most cases) and EventQueue.invokeAndWait (one case where the result from the user is needed to continue).

Moved GUI operations to the EDT

---

core/src/processing/opengl/PGraphicsOpenGL.java

Save now creates opaque images from primary OpenGL surface (#3031)

---

app/src/processing/app/contrib/ContributionListing.java

The contributions listing is now downloaded into a temporary file first. Once the listing is downloaded, the old ```contributions.txt``` file is deleted, and the temporary file is then renamed to ```contributions.txt```. This is required because the local copy of the ```contributions.txt``` (strangely enough) does not get updated sometimes (although this error is not easily reproducible by locally modifying the file, except when the file is from the processing website), as found [here](https://github.com/processing/processing/issues/2843). This PR fixes #2994.

contributions.txt now gets deleted and recreated instead of overwritten

---

java/src/processing/mode/java/JavaBuild.java

This addresses Issue #1046 which deals with launching exported linux applications from a different folder.  The problem was that the $APPDIR folder was not added to the classpath so it was not finding the data folder when the script was launched from a different location.

Allow exported linux applications to be launched from a different folder

---

app/src/processing/app/syntax/JEditTextArea.java

IllegalArgumentException not getting thrown when clicking in a second sketch window

---

java/libraries/net/src/processing/net/Server.java

As discussed in issue #3089 the processing.net.Server only cleans up dead clients when trying to write to them.  This patch has the server also check for dead clients while it is looking for available data to read.  The check is done in such a way so that a client that has died with unread data can still be read.  Additionally, the order of the clients should remain consistent and no client should be skipped.  I have included comments explaining the code so that in the future the non-obvious statements can be easily understood.

Server check for dead clients while checking for available messages

---

app/src/processing/app/contrib/ContributionListing.java

The implementation is a slightly modified version of @prisonerjohn 's suggestion [here](https://github.com/processing/processing/issues/2953#issuecomment-71921649). It has been tested to run well with both the current contribs.txt as well as a the contribs.txt [here](https://github.com/joelmoniz/G4P_Examples/blob/master/contributions.txt) which contains entries for the now  renamed ```examples-package``` type.

Contrib Manager does not stop parsing contribs.txt if an error exists

---

app/src/processing/app/Editor.java

Fix for #3136 and the discussion done in #3057 
The problem was that when Edit menu was opened without selecting any text the cut and copy options were disabled but when the menu was closed these options remained disabled and after that when cut/copy command was executed a doClick() was done on these items which were left disabled thus these command were not working.

Cut and Copy are now working .

---

app/src/processing/app/contrib/AvailableContribution.java
app/src/processing/app/contrib/Contribution.java
app/src/processing/app/contrib/ContributionListing.java
app/src/processing/app/contrib/ContributionManager.java
app/src/processing/app/contrib/LocalContribution.java
build/shared/lib/languages/PDE.properties
java/src/processing/mode/java/JavaEditor.java

This fixes #2566. It basically checks for whether the imported libraries are already installed or not. If one or more of them aren't, and if any/all of them are available, a dialog menu is displayed to the user listing the available, not installed libraries. Selecting ```Yes``` installs the libraries and runs the sketch, while selecting ```No``` simply runs the sketch directly (which eventually displays an error due to the missing library).
Note: This adds a new field, ```imports```, to the ```library.properties``` file, where the most commonly used headers of the library are listed.

Automatically install libraries that a user imports, if not already installed

---

app/src/processing/app/Base.java

This commit resolves fatal errors, such as those indicated by the dialog box "We're off on the wrong foot", and not the usually non-fatal errors which sometimes might be fatal (such as those indicated by the dialog box "Terrible News", which though often non-fatal, might sometimes be fatal, as in #3063), thereby partly fixing the issue described in #3068.

Fatal errors now kill processing, enabling building it again without killing it manually without using the Task Manager

---

java/libraries/net/src/processing/net/Client.java

This addresses issue #1400 dealing with a memory leak in the processing.net.Client which occurs when the parent "dispose" method is not unregistered if the client is stopped.  Rather than trying to track the state of several different variables, I've just declared an explicit boolean variable to track whether or not the dispose method needs to be unregistered.  Now when spawning and closing Clients the memory usage stays consistent.

Prevent memory leak of Client by unregistering parent dispose method

---

app/src/processing/app/syntax/JEditTextArea.java
build/macosx/appbundler/native/main.m

Horizontal scroll works but it is a little wonky because of the multiple scroll events from Apple's inertia scroll.
This PR also edits the native cocoa wrapper to disable inertia scrolling (See https://developer.apple.com/library/mac/releasenotes/DriversKernelHardware/RN-MagicMouse/). According to Apple that should work, but I'm not sure it does anything.
Fixes #180

Fix multi-touch horizontal scrolling on OSX

---

core/src/processing/core/PGraphics.java

Fix for #3028   
The spaces are not carried to the next line instead they are ommited .  
I am not sure if this is the required behaviour. Should the spaces before the first word in the line be printed ?

textAlign Right print correctly

---

app/src/processing/app/Base.java
app/src/processing/app/Mode.java

This reorganizes the examples manager tree and changes the `Add Examples` label into a button. Also includes misc refactoring code cleanliness and readability.

Refactor examples manager window: Fixes #3133

---

app/src/processing/app/ColorChooser.java

Previously, the whole window would show a crosshairs cursor when you hovered on it. Now only the slider and range components do.

Fix ColorChooser cursor

---

core/src/processing/core/PApplet.java

It's coming up in the wrong place on the Javadoc because its method is commented out.
Already mentioned at #3205 but you wanted it in a separate commit.

PApplet.java: disable a doc comment

---

core/src/processing/data/JSONObject.java

This puts the third parameter in `saveJSONObject(json, filename, options)` to some use. Main use case is storing big amounts of JSON data without wasting space on disk.

Add option to save JSON in compact form

---

core/src/processing/opengl/PGraphicsOpenGL.java

Tested in 3.0a5, latest does not run for me.
Fixes #3193.

Removed extra edges in sphere tesselation (#3193)

---

java/src/processing/mode/java/JavaEditor.java
java/src/processing/mode/java/JavaMode.java
java/src/processing/mode/java/tweak/SketchParser.java

This pull request fixes issue #3208 as well as:
- tweak init functions were moved to the end of setup.
- parser now skips comment blocks
- parser skips global assignments

TweakMode fix to issue #3208

---

app/src/processing/app/PreferencesFrame.java

Fix for #3231 
pack() is getting called twice as mentioned at https://netbeans.org/bugzilla/show_bug.cgi?id=79967
this might also fix the bug #3212 in Mac.
Also made the window non resizable.

Enhan pref windoe

---

app/src/processing/app/contrib/ContributionManagerDialog.java

The message is set to null so that every time the retry button is hit no previous error is displayed in the status.
P.S - just fooling around the Contribution Manager code to get familiar with the code for GSoC.

The error message in Contribution Manager is set to null on hitting retry

---

app/src/processing/app/Preferences.java

Fix for #1476 
Another important feature could be to add a new tab or something like that in the preference window so that user can set proxy at any time.  
This would particularly be useful for those people whose proxy server allows connection for only a specific period of time and then they have to switch to another proxy. As going to preference.txt and changing it doesn't look cool.
I will file a separate issue in this regard , meanwhile this works for system proxy as well as if proxy is set in preferences.txt.

System proxy getting used by deafult

---

app/src/processing/app/EditorHeader.java

This is a possible fix for #1968 and other duplicates of this issue. It causes the tab menu to lock to the right of the window when there are too many tabs to display and it doesn't render tabs which would interfere with the menu. Resulting in something that looks like this if there are too many tabs to render.
The only potential issue I see is that there is no indication that more tabs are hidden off screen. It might make sense to add another 'tab' which indicates more tabs are hidden (an ellipses or something). 
Hope this fixes this issue

Potential Tab menu fix

---

app/src/processing/app/Preferences.java
build/shared/lib/defaults.txt

Fix for #2643 
This should most probably fix the issue.
@benfry the field to be added to support socks proxy is `socksProxy.host` and `socksProxy.port` in the preference.txt . This should be added somewhere in the documentation and i am not sure where.

Added socks support in Processing

---

java/src/processing/mode/java/JavaEditor.java

Modified the Java mode to use the methods provided by the SketchCode class to access the code. This allows the times to update and fixes the issue brought up in #3222

Fix for breakpoints causing a reload prompt

---

app/src/processing/app/ChangeDetector.java

Adds a buffer of 1000 ms to the file change detection to fix a bug where the file modified time which processing recorded was different from that recorded by java. As discussed in #3222

Added buffer to file detection time

---

app/src/processing/app/Base.java

This resolves #3369, which was occurring because the `message` passed to the `showBadnessTrace()` function had new lines in it that weren't replaced with <br/> tags.

Mode problems dialog now displays vertically

---

app/src/processing/app/Sketch.java
build/shared/lib/languages/PDE.properties
build/shared/lib/languages/PDE_de.properties
build/shared/lib/languages/PDE_el.properties
build/shared/lib/languages/PDE_es.properties

This PR adds in a couple of key-value pairs into PDE.properties file from the app/Sketch.java that were hard-coded so far. This should complete the internationalization of app/Sketch.java.

Add missing internationalization in app/Sketch.java

---

core/src/processing/opengl/PGraphicsOpenGL.java

When enabling/disabling depth sorter, flush() has to execute before switching the sorter on/off.

Fix NullPointerException in DepthSorter

---

java/src/processing/mode/java/Commander.java

Just a reversal of c600540. This has been tested Linux&rarr;Linux and Linux&rarr;Windows.

Fix #2760: allow exports to other platforms again.

---

app/src/processing/app/contrib/LocalContribution.java
app/src/processing/app/contrib/ModeContribution.java

If the NoClassDefFoundError is caught for JavaMode, reinits the urlclassloader. (fixes #3443)

Fixes java mode loading

---

java/libraries/pdf/examples/LargePage/LargePage.pde

Environment: Ubuntu 14.10
Version: 3.0 alpha 0238
I tried an example of PDF library named "LargePage," and I had difficulty in finding the generated PDF file.
The comment in LargePage says "The file is saved to the sketch folder," but I think this is unfriendly because we usually open examples from "File->Examples..." so we don't care about where the sketch folder is.
Fortunately, we can open the sketch folder by "Sketch->Show Sketch Folder." I added a comment about this.

Added a comment in LargePage

---

core/src/processing/opengl/PGraphicsOpenGL.java

Fixes #3476
1) Arrays were not resized
2) There was a wrong index when rotating right

Sorter: Fix out of bounds exceptions

---

core/src/processing/opengl/PGraphicsOpenGL.java

Remove duplicate curve vertex

---

core/src/processing/core/PGraphics.java
core/src/processing/core/PShape.java
core/src/processing/core/PShapeSVG.java
core/src/processing/opengl/PGraphicsOpenGL.java
core/src/processing/opengl/PShapeOpenGL.java

Load rectMode and ellipseMode from parent.
Unify signatures and make them all work. This is the full list of available signatures:
```
createShape(POINT, x, y);
createShape(LINE, x1, y1, x2, y2);
createShape(LINE, x1, y1, z1, x2, y2, z2);
createShape(TRIANGLE, x1, y1, x2, y2, x3, y3);
createShape(QUAD, x1, y1, x2, y2, x3, y3, x4, y4);
createShape(RECT, a, b, c, d);
createShape(RECT, a, b, c, d, radius);
createShape(RECT, a, b, c, d, tl, tr, br, bl);
createShape(ELLIPSE, a, b, c, d);
createShape(ARC, a, b, c, d, start, stop);
createShape(ARC, a, b, c, d, start, stop, arcMode);
createShape(BOX, a);
createShape(BOX, a, b, c);
createShape(SPHERE, r);
```
Fixes #2646
Fixes #3018

Remove mode parameters from createShape(), fixes parameter collision issues

---

core/src/processing/core/PConstants.java
core/src/processing/core/PGraphics.java
core/src/processing/opengl/PGL.java
core/src/processing/opengl/PGraphicsOpenGL.java

Adds new hint ENABLE_DEPTH_READING, which will cause multisampled PGraphics to also downsample their depth and stencil buffers (apart from color buffer).

Feature: depth reading

---

app/src/processing/app/syntax/PdeInputHandler.java

Some keyboard layouts use third level (Ctrl+Alt+?) to input important characters. They should not be filtered out as menu mnemonics, see #3536 for details.
Fixes #3536

Do not filter Ctrl+Alt+? out as menu mnemonics

---

app/src/processing/app/ui/EditorHeader.java

Menu says Ctrl+Shift+D, but the shortcut used Alt.

Fix delete tab shortcut

---

java/src/processing/mode/java/JavaEditor.java
java/src/processing/mode/java/tweak/SketchParser.java

This PR fixes #3562.
TweakMode init functions:
```java
tweakmode_initAllVars();
tweakmode_initCommunication();
```
are placed now right after the call to size.
In addition, the parser now have a function ignore list. Right now it ignores all numbers in the 'settings' and 'setup' functions.

tweakmode: place tweak init function right after the size function

---

java/src/processing/mode/java/debug/LineID.java

This PR resolves #3552.
The issue was an off-by-one-error when a line consists purely of white-spaces.

Breakpoints don't 'jump' after hitting Enter on blank line

---

app/src/processing/app/Base.java
app/src/processing/app/Library.java
build/build.xml
core/build.xml
core/library/export.txt
core/src/processing/opengl/PGraphicsOpenGL.java
core/src/processing/opengl/PSurfaceJOGL.java
core/src/processing/opengl/shaders/LightVert-vc4.glsl
core/src/processing/opengl/shaders/TexLightVert-vc4.glsl
core/src/processing/opengl/shaders/TexLightVert.glsl
java/src/processing/mode/java/Commander.java
java/src/processing/mode/java/JavaBuild.java
java/src/processing/mode/java/runner/Runner.java

Supersedes #3566, only changes JOGL profile on ARM.

Second bunch of arm patches (v5)

---

core/src/processing/awt/PGraphicsJava2D.java

No longer needed because primary surface is now ARGB
https://github.com/processing/processing/commit/f3b72c709cc1db96edf06176cd39eee2c233127b

Remove alpha filler

---

core/src/processing/opengl/PGL.java
core/src/processing/opengl/PJOGL.java
core/src/processing/opengl/PSurfaceJOGL.java
core/src/processing/opengl/shaders/LightVert.glsl
core/src/processing/opengl/shaders/TexLightVert.glsl

- Now using at least OpenGL ES 2.0
- Getting depth and stencil bits is now done through capabilities
- Enabling and disabling textures was deprecated with fixed-function pipeline, removing
- Shaders on MACOSX now have to use GLSL 1.30, doing a little bit of preprocessing to get our shaders there
- Minor adjustments to shader code so it does not throw warnings on pedantic Intel cards

Remove fixed-function pipeline

---

core/src/processing/opengl/shaders/LightVert-vc4.glsl
core/src/processing/opengl/shaders/TexLightVert-vc4.glsl
java/src/processing/mode/java/Commander.java
java/src/processing/mode/java/runner/Runner.java

The remaining patches that I carried in my branch.

Third bunch of arm patches

---

core/src/processing/opengl/PGL.java

MACOSX does not advertise extensions which were included into OpenGL specification, so we also have to check for OpenGL version.
Fixes framebuffer unsupported error.

Improve OpenGL extensions checks

---

core/src/processing/core/PApplet.java
core/src/processing/core/PConstants.java
core/src/processing/core/PGraphics.java
core/src/processing/event/KeyEvent.java
core/src/processing/opengl/PSurfaceJOGL.java

P2D and P3D:
- keyTyped events are now generated (dead keys do not combine and fire separate event though)
- key auto-repeat is disabled by default (you can enable it by new ENABLE_KEY_AUTO_REPEAT hint)
Fixes #3582
Related #1622

OpenGL key event improvements

---

core/src/processing/javafx/PGraphicsFX2D.java

Rect was using coordinates of it's second corner as its width/height

FX - fix rect size

---

app/src/processing/app/ui/Editor.java

...so that when we undo we're moving to where we began,
not where things would have been in the edited text after.
Fix for #707.

storing caret for undo at start of edit

---

build/build.xml

ARM started offering builds for 64 bit ARM (ARMv8), which made them rename the download file.

Fix ARM JDK download for 8u60

---

app/src/processing/app/contrib/ContributionListPanel.java
app/src/processing/app/contrib/ContributionManagerDialog.java
app/src/processing/app/contrib/StatusPanel.java
app/src/processing/app/contrib/UpdateContributionTab.java

I hope that this is the correct implementation.  
Shouldn't there be a field in Toolkit which is simply set to 1 or 2 depending upon the resolution.
But the notification circle is a little small as can be seen above.

Icons are implemented

---

core/src/processing/javafx/PSurfaceFX.java

Make key events behave similar to Java2D.
Returned key chars in pressed/released events are always uppercase, but keyCodes are correct.
Key typed events give correct key char, but zero keyCode.
All non-alphanumeric keys I could find on my keyboard now return key char PConstants.CODED.

FX - Make key events little bit more sane

---

core/src/processing/opengl/PGL.java
core/src/processing/opengl/PJOGL.java

Remove legacy functions and constants which are available only in GL2, because we are not getting GL2 compatible implementations anymore. Users who want to use these functions can still get the GL2 interface from PGL, but it's going to be null most of the time.
Yeah, and since we are breaking things, I corrected a typo in a function name.
Fixes #3674

Remove legacy GL functions from PGL

---

app/src/processing/app/ui/Editor.java

Undoing an auto-format now happens in one step, instead of having to undo (to clear the current sketch) and undo again (to get back the pre-formatted text).
This PR fixes (or at the very least, fixes one of several possible causes of) #3003.

Make auto-format into a compund edit

---

app/src/processing/app/contrib/ContributionManagerDialog.java
app/src/processing/app/contrib/UpdateContributionTab.java

Fix for #3689 
@alignedleft @benfry 
The scrollPane gets the focus by default. You can see the effect this is causing by opening the CM, then switching to Libraries tab, then pressing the `Down Arrow` key.  
Should scrollPane be the item getting the default focus in a tab ?

ScrollPane gets the focus by default

---

app/src/processing/app/ui/Editor.java

This PR fixes the (second) "undo-autoformat-clears-text" issue triggered as described [here](https://github.com/processing/processing/issues/3003#issuecomment-133811839).

Fix (another) issue with undoing auto-format

---

app/src/processing/app/contrib/ContributionTab.java

Width fixing

---

core/src/processing/javafx/PSurfaceFX.java

When your sketch ran slower than target frame rate, FX was blocked and
was drawing to the screen only every few seconds. This eventually
resulted in OutOfMemoryError as it's internal draw buffer was not
flushed.

FX - framerate fix

---

core/src/processing/core/PGraphics.java

This block seems to be out of place. It is entered when the current word
has zero length. It's not possible to tell whether the string fits on
the line or not at this place. Besides, the same condition is already
handled below.

Render text starting with space properly

---

java/src/processing/mode/java/pdex/ErrorCheckerService.java
java/src/processing/mode/java/preproc/PdePreprocessor.java

catch: if they have a method in their body named setup or draw, mode is
always (sometimes incorrectly) detected as Active
Fixes #533

Allow anonymous classes in static mode

---

java/src/processing/mode/java/pdex/ErrorCheckerService.java
java/src/processing/mode/java/preproc/PdePreprocessor.java

Fixes #3799
- scope is taken into account when determining the sketch mode and
looking for size()
- error checker received some love and now understands JAVA mode
Modes:
- JAVA sketch contains "public class [sketchName] extends PApplet" in
the global scope
- ACTIVE sketch contains a method declaration in the global scope
- STATIC sketch is everything else
size() parsing:
- JAVA sketches: no parsing
- ACTIVE mode: if there is setup() in global scope, we look there for
the first occurrence, no parsing otherwise
- STATIC sketches: first occurrence of size() in global scope

Make preprocessor scope-aware

---

core/src/processing/core/PApplet.java

Leftovers from working on parser

Make the PApplet regex cache LRU

---

core/src/processing/core/PConstants.java
core/src/processing/core/PGraphics.java
core/src/processing/opengl/PGL.java
core/src/processing/opengl/PGraphicsOpenGL.java
core/src/processing/opengl/PJOGL.java
core/src/processing/opengl/PSurfaceJOGL.java

- Asnychronous image saving for all renderers
- Asynchronous pixel download for OpenGL renderers
- both enabled by default, use DISABLE_ASYNC_SAVEFRAME and ENABLE_ASYNC_SAVEFRAME hints
- small OpenGL fixes
fixes #3569

Async saveFrame

---

java/src/processing/mode/java/pdex/ErrorCheckerService.java
java/src/processing/mode/java/pdex/JavaTextArea.java

- catch exception when multiline comment is not closed
- replace codePointAt() with charAt()

Error checker/suggestions fixes

---

java/src/processing/mode/java/pdex/ErrorCheckerService.java

Hide a useless error which is produced when a line ends with an identifier without a semicolon. "Missing a semicolon" is also produced and is preferred over this one.
(Syntax error, insert ":: IdentifierOrNew" to complete Expression)
See: https://bugs.eclipse.org/bugs/show_bug.cgi?id=405780

Hide useless error in error checker.

---

core/src/processing/opengl/PSurfaceJOGL.java

These are BACKSPACE, TAB, ENTER, ESC, and DELETE. Enter and Return can't be distinguished, both are reported as keyCode 10 (keyChar \n).

Convert all documented hacky keys in OpenGL

---

app/src/processing/app/Base.java
app/src/processing/app/contrib/ContribProgressMonitor.java
app/src/processing/app/contrib/ContributionListing.java
app/src/processing/app/contrib/ContributionManager.java
app/src/processing/app/contrib/DetailPanel.java
app/src/processing/app/contrib/LocalContribution.java
app/src/processing/app/contrib/UpdateListPanel.java
app/src/processing/app/ui/Editor.java

Requested for #3518
See https://github.com/processing/processing/issues/3518#issuecomment-143768021

CM: Send update count to Editors

---

app/src/processing/app/Util.java
app/src/processing/app/contrib/AvailableContribution.java
app/src/processing/app/contrib/LocalContribution.java

Clean up delete dir function

---

app/src/processing/app/tools/InstallCommander.java

Fixes #3996 
Tested both running with and without `--build`. The fix works as expected. Running processing-java with the `--build`-option doesn't steal focus anymore.
This change makes the /usr/local/bin/processing-java shell script look like this for me:
```
#!/bin/sh
OPTION_FOR_HEADLESS_RUN=""
for ARG in "$@"
do
if [ $ARG = "--build" ]; then
OPTION_FOR_HEADLESS_RUN="-Djava.awt.headless=true"
fi
done
cd "/Users/martin/git/processing/build/macosx/work/Processing.app/Contents/Java" && /Users/martin/git/processing/build/macosx/work/Processing.app/Contents/PlugIns/jdk1.8.0_51.jdk/Contents/Home/jre/bin/java -Djna.nosys=true $OPTION_FOR_HEADLESS_RUN -cp "ant-launcher.jar:ant.jar:core.jar:jna.jar:pde.jar:core/library/core.jar:core/library/gluegen-rt-natives-linux-amd64.jar:core/library/gluegen-r …
```

processing-java: Run in headless mode with --build

---

core/src/processing/opengl/PSurfaceJOGL.java

After some testing, it appears that fixed rate scheduling tries to catch
up later when it runs slower than desired, creating weird speedups when
the load decreases. Turning it back off.

Turn off fixed rate scheduling in OpenGL

---

java/src/processing/mode/java/tweak/SketchParser.java

This is an improved version of my previous pull request after some friendly hints by @galsasson. This one has even less changes and should be more transparent.
We now maintain the ignore-lists for functions in separate lists for the different tabs.

Improved fix for Issue #4017 where tweak mode ignores some numbers in a second tab

---

java/src/processing/mode/java/JavaEditor.java

Check if #3983 is still an issue

Add error checker document listeners to all tabs

---

app/src/processing/app/ui/Recent.java

Recent menu was keeping Editors in memory

Fix memory leak in Recent

---

java/src/processing/mode/java/preproc/PdePreprocessor.java

Trying to run sketch with setup() without a body would crash the preprocessor. Now it gives correct error message.

Prevent preprocessor from crashing when setup() has no body

---

core/src/processing/opengl/PGL.java

Context is now taken into account, so it's not just blind search and replace anymore.
Fixes #3961
Fixes #3968

Improve shader preprocessor with regex-fu

---

app/src/processing/app/ui/Editor.java

Added code to let the green traffic light button on OSX activate native fullscreen mode.
Resolves #3993

Add OSX native fullscreen

---

core/src/processing/core/PGraphics.java

Change in 6f5328295e871a96f4d8cee08eecf25d59c5263a was getting
overwritten from PGraphics when ant building.

Prevent nowebref from coming back

---

build/linux/install-arm.sh

To point to download.processing.org (currently 404).

ARM Installer script: Change URL

---

build/windows/config.xml
java/src/processing/mode/java/pdex/ASTGenerator.java
java/src/processing/mode/java/pdex/CompletionCandidate.java

Because of a JRE bug, code completion will occasionally freeze the PDE. Never seen this one before, however, it happened to me three times in a row while I was giving a lecture today and I had to kill the PDE and write all the code again. I can reproduce it back to beta 7. It is caused by JIT compiler, workaround is to disable it for this particular method. See https://bugs.openjdk.java.net/browse/JDK-8060036 and http://kingsfleet.blogspot.com.br/2014/11/but-thats-impossible-or-finding-out.html

Workaround for JRE bug freezing the PDE

---

app/src/processing/app/ui/PreferencesFrame.java

This patch fixes the issue -> https://github.com/processing/processing/issues/4272
***Color selector icon*** in the ***Preferences*** window will now be able to update it's color depending upon user's color selection in Color Selector panel.

 'Background Color when Presenting' not visible on Preferences window

---

java/src/processing/mode/java/AutoFormat.java

Simple enums without semicolons and labels that aren't in a method body were handled incorrectly, the first because it didn't properly recognize that the statement had ended, and the second because `tabs` was reduced from 0 to -1, "corrected" from -1 to 0, and then incremented up to 1.

Fix minor autoformatter bugs. Fixes #4185.

---

core/src/processing/core/PApplet.java

The current Linux commands used, `gnome-open` and `kde-open`, aren't standardized, and I don't even have `gnome-open` on my (Debian) Gnome 3 machine.
I've also removed the statement about there being no standard way to open URLs on Linux, since `xdg-open` is supposed to work across all desktops and dates from 2006.

Use xdg-open in PApplet#launch(String)

---

java/src/processing/mode/java/pdex/ASTGenerator.java
java/src/processing/mode/java/pdex/JavaTextAreaPainter.java

ASTGenerator.java: Stops there being loads of red text (null pointer exceptions) when you open the context menu with the compiler broken as I reported in #4090. (I'm still not sure what caused #4090, but since it went away when I deleted my configuration files I assumed that it wasn't a real bug.)
JavaTextAreaPainter.java: I just noticed the very odd code that had two different checks for the empty string (with one unreliable and using `==`) and thought that this made more sense.

Minor fixes to Java Mode

---

java/src/processing/mode/java/runner/Runner.java

Regarding #4149 and against the better advice of #2623
Currently recursive functions only output this:
crashed in event thread due to Timeout occurred while waiting for packet 29.
org.eclipse.jdi.TimeoutException: Timeout occurred while waiting for packet 29.
at org.eclipse.jdi.internal.connect.PacketReceiveManager.getReply(PacketReceiveManager.java:186)
at org.eclipse.jdi.internal.connect.PacketReceiveManager.getReply(PacketReceiveManager.java:197)
at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:191)
at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:226)
at org.eclipse.jdi.internal.ThreadReferenceImpl.frames(ThreadReferenceImpl.java:257)
at org.eclipse.jdi.internal.ThreadReferenceImpl.frames(ThreadReferenceImpl.java:240)
at …

Make the error message for stack overflows clearer

---

java/src/processing/mode/java/JavaEditor.java

When nothing is selected in editor, and then if someone clicks on Help->Find in Reference or Ctrl+Shift+F, then message gets displayed on message area as **'First Select a word to find in the Reference.'**

message when reference is find out on nothing selected

---

app/src/processing/app/tools/InstallCommander.java

Related to #3996.
Now it doesn't give an error when there is quotation in the command line args.
Related comments:
https://github.com/processing/processing/issues/3996#issuecomment-154859783
https://github.com/processing/processing/issues/3996#issuecomment-155404233
I have tested that this fixes the issue reported in the first comment.

Small fix to processing-java generation

---

java/libraries/io/examples/Interrupt/Interrupt.pde
java/libraries/io/examples/SimpleInput/SimpleInput.pde
java/libraries/io/examples/SimpleOutput/SimpleOutput.pde

Even the Raspberry Pi Foundation used GPIO numbers over (congruous) physical pin numbers:
https://www.raspberrypi.org/learning/introduction-to-processing/worksheet-2/
Switch our examples as well, so that it they're more clear and hardware-agnostic.

IO: Use GPIO numbers in examples

---

app/src/processing/app/syntax/im/CompositionTextManager.java
app/src/processing/app/syntax/im/CompositionTextPainter.java
app/src/processing/app/syntax/im/InputMethodSupport.java

current InputMethod of syntax.im package was only support Japanese. the Japanese Input Method and Chinese Input Method(this called pinyin) are similar system. but Korean Input Method is not.
I rewrited code for CJK support. and I tested only Windows8.1 64bit(Japanese). 
I dont test Mac OSX. (need test)
#2968
#3860
#3475
Language | Commited text Trigger Key | toggle key to english
--- | --- | --- | ---
Japanese | Enter key or space key | hankaku Key
Chiese(Pinyin) | space key | left shift key
Chiese(Bopomofo) | space key  | left shift key
Korean(Hangl) | NO | right alt key
korean 
japanese
chinese
#3475 fixed

Fixed InputMethod Chiese/Japanese/Korean support.

---

java/src/processing/mode/java/MarkerColumn.java

This pull request addresses #4322 and provides alternative solution of this problem than #4324, as suggested by @JakubValtar.
Instead of using Java synchronization mechanisms, which would sometimes cause UI thread to block until background thread in `updateErrorPoints` finishes execution, the work from background thread is now entirely done on the UI thread, which entirely eliminates synchronization issues (that's why all `synchronized` blocks were removed from `updateErrorPoints`).
Also, `errorPoints` redeclaration is fixed in order to be consistent with the initial declaration (which allows future `errorPoints` references from different threads to be safe - although maybe using `synchronizedList` now is unnecessary, given that all `errorPoints` references are from UI thread now?)

Move updateErrorPoints background work to UI thread

---

build/build.xml

As discussed in Issue #4308 adding arm support for .deb broke the .deb build process for non-arm devices.  I've tested it and this commit allows .deb to be built on non-arm devices again.  I have not tested to verify if .debs can still be built on the raspberry pi.  Perhaps @gohai can verify this?

Fixes non-arm linux deb build process

---

app/src/processing/app/ui/Editor.java
java/src/processing/mode/java/JavaEditor.java
java/src/processing/mode/java/MarkerColumn.java
java/src/processing/mode/java/debug/LineHighlight.java
java/src/processing/mode/java/pdex/ASTGenerator.java
java/src/processing/mode/java/pdex/CompletionPanel.java
java/src/processing/mode/java/pdex/ErrorCheckerService.java
java/src/processing/mode/java/pdex/JavaTextArea.java
java/src/processing/mode/java/pdex/SketchOutline.java
java/src/processing/mode/java/pdex/TabOutline.java
java/src/processing/mode/java/pdex/XQPreprocessor.java

- resolve listener madness in JavaTextArea
- remove dependencies on ErrorCheckerService and ASTGenerator
- get rid of some useless SwingWorkers
- remove unused line bg & gutter color support from JavaEditor and JavaTextArea
- minor JavaEditor and JavaTextArea cleanup

JavaMode cleanup

---

core/src/processing/awt/PGraphicsJava2D.java

Fix for #4019 .
It was another setting that getGraphics() was nuking.

Reapplied blendMode setting.

---

app/src/processing/app/Platform.java
core/src/processing/core/PApplet.java

URLDecoder was being used for path decoding, even though it can't handle
RFC2396 encoding. This resulted in plus characters being removed and
possibly other weirdness.
See https://docs.oracle.com/javase/8/docs/api/java/net/URL.html
> The recommended way to manage the encoding and decoding of URLs is to use URI, and to convert between these two classes using toURI() and URI.toURL(). The URLEncoder and URLDecoder classes can also be used, but only for HTML form encoding, which is not the same as the encoding scheme defined in RFC2396.
Fixes #4417

Fix file path decoding

---

core/src/processing/opengl/PGL.java

glGenerateMipmap is supported on GL ES 2.0 and above. Tested on Raspberry Pi w/ binary GLES2 driver.

Add automatic mipmap support to GLES2

---

core/src/processing/opengl/PSurfaceJOGL.java

Before:
```
java.lang.RuntimeException
at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:449)
at java.lang.Thread.run(Thread.java:745)
```
After:
```
java.lang.RuntimeException: Waited 5000ms for: <fb397, c84a66>[count 1, qsz 0, owner <main-Display-.bcm.vc.iv_nil-1-EDT-1>] - <main-FPSAWTAnimator#00-Timer0-FPSAWTAnimator#01-Timer1>
at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:452)
at java.lang.Thread.run(Thread.java:745)
```

Be more verbose with drawExceptions with cause null

---

app/src/processing/app/ui/SketchbookFrame.java

After this patch, grayed-out text "Empty Sketchbook" will appear on sketchbook window whenever sketchbook is empty and is opened.

Empty sketchbook message when sketchbook is empty

---

java/src/processing/mode/java/Commander.java

this fix for #1633.
a Windows Command Prompt and Powershell Prompot are not UTF-8 encoding. so I add condition for windows . (Platform.isWindows())

fixed a processing-java command encoding problem for Windows Prompt

---

java/src/processing/mode/java/JavaBuild.java

This PR addresses issue #4318 and allows exported linux applications to be launched via a symlink.

Add support for symlinks to exported applications in linux

---

app/src/processing/app/ui/Toolkit.java
build/shared/lib/languages/PDE_ja.properties

This is a pull request for #2886.
If a language is the CJK(The Chinese, Japanese and Korean), this patch load a system font.
the header and footer could draw correct font.

fix:load fallback font for CJK(The Chinese, Japanese and Korean).

---

java/libraries/net/src/processing/net/Client.java

This adds the requested feature (issue #4167) to allow reading a specific number of bytes from a network Client.  I have tested out the new function and it appears to be working well.

Added readBytes(max) to net library

---

java/libraries/serial/src/processing/serial/Serial.java

This adds the requested feature (issue #4167) to allow reading a specific number of bytes from the serial library.  It follows the exact same logic as the readBytes(max) function which has been implemented for the network library (see PR #4320).  I have not been able to test it beyond ensuring that it compiles hence the separate pull request.

Added readBytes(max) to serial library

---

java/src/processing/mode/java/JavaBuild.java

I had students export a sketch on their laptops and try it out on a Raspberry Pi, but this failed for most, since their memory settings in Preferences were at insanely high values. Perhaps for the time being, we could ignore those for ARM?

Ignore memory options when exporting for ARM

---

build/shared/lib/languages/PDE.properties
java/src/processing/mode/java/pdex/ErrorMessageSimplifier.java
java/src/processing/mode/java/pdex/Problem.java

Fixes #4228; is a duplicate of #4337 adjusted for some API changes.

PDEX: Add friendlier error message for HidingEnclosingType

---

app/src/processing/app/syntax/Brackets.java
app/src/processing/app/syntax/JEditTextArea.java

Fixes #4397 and  makes bracket matching work immediately after changing tabs. (Previously, you had to make an edit after changing tabs for the bracket matchers "offsets" variable to be invalidated.)
Also undoes one line from #4113:
````
if (offsets == null || offsets.get(offsets.size()-1) >= text.length())
````
If `offsets` contains an invalid offset, then there is a bug that needs fixing, because invalidate() hasn't been called when the document changed. So it doesn't make sense to just check for bad offsets and then call parse(), because it's likely that the bug will also manifest itself in other ways.

Fix bracket matching bugs.

---

app/src/processing/app/Mode.java

In this case, base is null. Fixes #4452.

Prevent InvocationTargetException when running processing-java

---

app/src/processing/app/syntax/JEditTextArea.java
app/src/processing/app/ui/Editor.java
app/src/processing/app/ui/FindReplace.java

This PR attempts to resolve #4280, fix #4302 and close #4303.
#4303 was mostly an issue with not considering `Replace All` as a compound edit. I have left `Replace`s to be individually undo-able, since technically each `Replace` i a distinct operation (unlike `Replace All`s, which all happen at once).
I had to modify the `JEditTextArea` a little for #4280, because the replacement happens from within there, and there's no `Editor` object accessible (and hence, the `Editor`'s compound edit methods can't be called). The `SyntaxDocument` has compound edit methods, but they were left blank, and never overridden, so I now have.
#4302 was a little tougher to crack, but primarily boiled down to each insert and deletion being considered a separate compound edit, with replacements (i.e., entries in …

Fix a few undo-related bugs

---

build/build.xml

JRE 8u91 or higher cause performance problems with the GL Video library - specifically: SimpleCapture example doesn't show a texture from USB-attached webcam on Raspberry Pi 2, and TwoVideos example doesn't play two videos smoothly.
This was tested with Processing compiled on the Pi (JDK 8u65b17), and processing-glvideo 2d6de36a33fde3573b335e9a95cc3e380466f328.
@benfry Spent all morning tracking down this regression ... would you mind if I re-spun the ARM tar-ball for 3.1 with this change? (Holding off with the Raspbian image for now)

Switch back to JRE 8u77 on ARM

---

app/src/processing/app/ui/Editor.java

Hello,
With this I think the issue #4249 is fixed and uncommenting the lines wont reduce the identation, and it will remain the way it was before uncommenting. :)
Would like to have some review on this!

Uncomment identation fix #4249

---

app/src/processing/app/contrib/ExamplesContribution.java
app/src/processing/app/syntax/SyntaxStyle.java
app/src/processing/app/syntax/im/CompositionTextManager.java
app/src/processing/app/syntax/im/CompositionTextPainter.java
app/src/processing/app/syntax/im/InputMethodSupport.java
build/.gitignore
build/build.xml
core/src/processing/core/PApplet.java
core/src/processing/core/PImage.java
core/src/processing/core/PShape.java
core/src/processing/core/PSurface.java
core/src/processing/data/JSONArray.java
core/src/processing/data/JSONObject.java
core/src/processing/data/Table.java
core/src/processing/data/XML.java
core/src/processing/opengl/LinePath.java
java/libraries/dxf/src/processing/dxf/RawDXF.java
java/libraries/io/src/processing/io/SPI.java
java/libraries/serial/src/processing/serial/Serial.java

I'm trying to significantly reduce the number of error messages from the `ant doc` command, so that the genuine errors can be seen and dealt with. Currently, for example, there's an unclosed bold tag over a lot of an online Javadoc page. (It seems to have been fixed in the original files now though.)
This isn't finished yet; I'd like some advice. This first commit was just running [GenerateDescriptions.py](https://github.com/processing/processing-docs/blob/master/java_generate/GenerateDescriptions.py) with some patching/manual editing of files where it was broken. This was so that if I needed to modify and rerun the script or XMLs later, the later commits' diffs wouldn't contain ordinary updates to XML files.
The second commit fixes most of the errors except those in the HTML and syntax …

Fix error messages from Javadocs

---

core/src/processing/core/PApplet.java
core/src/processing/core/PGraphics.java
core/src/processing/opengl/PGraphicsOpenGL.java

Block loadImage and requestImage when trying to load image which is being saved asynchronously.
It is expected that `loadImage()`/`requestImage()`/`save()`/`saveFrame()` will be called on main thread of the sketch. As of now, we don't provide any guarantees re: using PApplet/PGraphics from multiple threads.
Fixes #4218

Async save update

---

app/src/processing/app/platform/LinuxPlatform.java

Ubuntu doesn't have packages for Oracle's Java anymore. Will update Wiki too.

Update JVM warning text on Linux

---

build/build.xml
build/jre/src/Downloader.java

Addresses #4496. Enough to get JRE downloads to work again.

Fix Downloader

---

build/build.xml
core/src/processing/opengl/PSurfaceJOGL.java

The performance regression with 8u91 and above was figured out and worked around in version 1.0.2 of the GL Video library. See: https://github.com/gohai/processing-glvideo/commit/055a90cacd7c82c4b9e36fa9198a18c1947db8d6

ARM Updates

---

core/src/processing/core/PApplet.java

As pointed out by @jdf in #4501

Prevent NPE in loadImage() when called before setup()

---

app/src/processing/app/Language.java
app/src/processing/app/Platform.java
core/src/processing/core/PApplet.java

Fixes #4417
Java has problems dealing with UNC paths. See http://wiki.eclipse.org/Eclipse/UNC_Paths#Programming_with_UNC_paths to get an idea how bad it is. Scheme specific part should contain the whole decoded URI except the protocol name and following colon, which should shield us from Java parsing URL parts incorrectly.

Fix running PDE from network locations

---

core/src/processing/awt/PSurfaceAWT.java
java/src/processing/mode/java/pdex/JavaTextAreaPainter.java

Reported this to the CHIP team: Seeing some odd exception from deep within Java's awt classes ("Width (0) and height (0) must be non-zero"). This is triggered because the libX11 function XQueryBestCursor is returning a width and height of zero, which seems to be a bug. I am guessing that this will also pop up with other Java applications.
This makes things work on the CHIP w/ OS image 4.4 and latest packages. I also tested on OS X, but I am not familiar enough with the Tweak Mode to say for sure.

Add a temporary workaround for the CHIP

---

build/shared/lib/languages/PDE_ja.properties

In preferences window,
[cancel] button is too narrow for Japanese word "キャンセル"
so make it wider.
Before:
After:

Make preferences button wider for Japanese

---

app/src/processing/app/Base.java
app/src/processing/app/ui/Editor.java
build/shared/lib/languages/PDE.properties
build/shared/lib/languages/PDE_ja.properties

If you try to change the mode which is not compatible with the current mode,
the mode change is canceled silently and different mode is checked in mode menu popup.
Reproducing this issue:
1. Install Python mode.
2. Select Python mode.
3. Load any sample sketch.
4. Click mode menu popup, and select Java.
5. No message is shown and Java is checked in popup (but keeps Python mode.) 
This change fixes the issue,
if selected mode cannot handle current source,
show warning dialog and reselect old (current) mode.
This change added text strings for English and Japanese only.
Related #2615

Show warning message if mode cannot be changed

---

java/src/processing/mode/java/JavaInputHandler.java

Checking `editor.tabs.expand` is done just before the block,
so this condition is always met.

Simplify conditional branch

---

app/src/processing/app/ui/Editor.java

JavaMode visits all tabs on sketch load to extract breakpoints, so doc
is always set (except when running Tweak mode; it sets docs to null to
force reload). Other modes have null docs until the tabs are visited
manually.
Fixes #4555

Prevent NPEs when tab document is null

---

app/src/processing/app/syntax/InputHandler.java
app/src/processing/app/syntax/JEditTextArea.java
app/src/processing/app/syntax/im/InputMethodSupport.java
java/src/processing/mode/java/JavaInputHandler.java

Currently, when a user input any character using input method support, sketch is not marked as modified.
So no dialog popped up when the user tried to close the window or quit the application and lost the changes.

Set sketch as modified when any character committed using input method

---

app/src/processing/app/syntax/im/InputMethodSupport.java

`inputMethodTextChanged` is called each time
when a user pressed key and keeps modifying a text on input method support.
In the time, code hasn't been modified yet,
but calling `handleInputMethodCommit` makes sketch as modified.
Code is modified when the user pressed enter key to decide the input,
and then `committedCount` becomes non zero.

Insert string when it is committed

---

core/src/processing/core/PGraphics.java

Got burned by not setting pixelWidth and pixelHeight properly.
Fixes #4578

Fix resizing targets for async save

---

app/src/processing/app/syntax/JEditTextArea.java
app/src/processing/app/syntax/TextAreaPainter.java
app/src/processing/app/ui/Editor.java

Allows multiple tabs at once and lifts responsibility for print rendering from TextAreaPainter. This was to avoid wrapping every other statement of TextAreaPainter in `if (!printing)` blocks, as there are so many features (eg. line numbers on a blue background) in it that would otherwise need suppressing when printing. It also makes line wrapping work.  I've only tested on Linux.
Fixes #50.
Closes #213 (as I think I've deleted all the code that could have been responsible).

Use HTML to print

---

app/src/processing/app/ui/Toolkit.java
build/build.xml

This has only been lightly tested on OS X and ARM Linux. The createFont function could be also simplified in the future by mandating all custom files to be placed in shared/fonts.
Note: this still prints "Source Code Pro not available, resetting to monospaced" (and will change preferences.txt accordingly). This seems to be because the first `createFont("SourceCodePro-Regular.ttf")` only comes after the call to `updateAppearance()`. (The Source _Sans_ Pro fonts are instead created & registered _before_ the `updateAppearance()`).
Will be busy with real life the next week, but I can look some more into this next weekend!

Simplify font situation to make it possible to use vanilla JRE trees

---

app/src/processing/app/ui/Toolkit.java

Wanted to at least remove the misleading comment that the last fallback is for Linux only, but ended up removing the other cases too (which are hopefully not needed anymore).

Cleanup createFont

---

core/src/processing/opengl/PJOGL.java

Calling glGetShaderiv to retrieve the program log length produces a
GL_INVALID_OPERATION error and length < 0, preventing the return of the
actual info log. This fix replaces the call to glGetShaderiv with
glGetProgramiv.
Closes #4659

Call glGetProgramiv to retrieve program log length

---

app/src/processing/app/contrib/DetailPanel.java
app/src/processing/app/contrib/StatusPanel.java

A fix for #4696 that adds some checks to avoid displaying `null` in the contribution manager. Note that `prettyVersion` becomes a `"null"` **string** when the base version is invalid - this is reflected in the checks.
Check that PeasyCam, a library that currently has an invalid contribution file, has no `null` versions displayed in the contribution manager:

CM: Fix null versions in the contribution manager (#4696)

---

core/src/processing/data/JSONArray.java
core/src/processing/data/JSONObject.java

Changed the access modifier of get()

---

app/src/processing/app/contrib/ContributionTab.java

Adds a cross button on the right side of the search field in CM. Currently a "X" is being displayed but can be replaced by a icon.
Might be a cool feature. Looks like below on linux -

Added the remove filter feature

---

java/src/processing/mode/java/pdex/SourceUtils.java

Replace non-capturing groups by positive lookahead and lookbehind, because they don't consume the source String and allow for first and last group to overlap when two constructors are directly nested.
Fixes #4652

Fix nested type constructors raising error

---

app/src/processing/app/syntax/JEditTextArea.java
app/src/processing/app/syntax/PdeTextAreaPainter.java
app/src/processing/app/syntax/SyntaxDocument.java
app/src/processing/app/syntax/TextAreaPainter.java
app/src/processing/app/syntax/TokenMarker.java
app/src/processing/app/syntax/TokenMarkerState.java

TokenMarker now serves as a holder for keyword list and to provide
marking logic. I extracted the rest into TokenMarkerState. Each tab now
has its own state, preventing bugs by leaking TokenMarker state between
tabs amd Editor instances.
There is no need to recompile any Modes, however TokenMarker should be
redesigned in the next major version and Modes updated accordingly.
For more details read TokenMarkerState header.
Fixes #4522

Extract state from TokenMarker

---

java/src/processing/mode/java/pdex/ErrorMessageSimplifier.java
java/src/processing/mode/java/pdex/JavaProblem.java
java/src/processing/mode/java/pdex/PDEX.java
java/src/processing/mode/java/pdex/PreprocessedSketch.java
java/src/processing/mode/java/pdex/PreprocessingService.java
java/src/processing/mode/java/pdex/SourceUtils.java

Fixes #4702
We should consider automatically completing blocks when user types { and hits enter, otherwise "Missing right curly bracket }" is the only error shown until the block is closed.
Edit: I also appended fix for #4748 *Can't update libraries - JARs are locked* because it would otherwise conflict with this PR.
Libraries imported in opened sketches will be still locked by latest
preprocessed CompilationUnit. Otherwise we would have to copy library
jars somewhere else so they can be available to CompilationUnit while
Contribution Manager updates original unlocked jars.

Report missing brace in correct tab, suppress other errors until fixed

---

core/src/processing/javafx/PGraphicsFX2D.java

Matrix stack could overflow in a very special case when beginShape() was
called while strokeWeight=1 and then strokeWeight was changed before
endShape(). This PR makes sure matrix is popped correctly even when user
changes strokeWeight in the beginShape()/endShape() block.
Decided to bug user only when necessary and not show warining when user
changes strokeWeight in the beginShape()/endShape() block, same as in
JAVA2D. Otherwise we could add checks for all the other things which are
mentioned in the docs, but it would be hell to maintain and use.
Fixes #4206

FX: Prevent matrix stack overflow

---

core/src/processing/javafx/PSurfaceFX.java
core/src/processing/opengl/PSurfaceJOGL.java

OPENGL and FX renderers will now correctly report button which triggered
this pressed/released event (same as JAVA2D).
Previously:
- OPENGL would report currently pressed buttons in order LEFT, CENTER,
RIGHT regardless of which button triggered the event. E.g. when holding
LEFT and presing RIGHT, LEFT would be reported. When holding CENTER and
pressing LEFT, LEFT would be reported
- FX would report only first button which is down, so in RELEASE event
button would be missing
Now:
- event contains only button which triggred this event (button just
pressed or just released)
Fixes #4361

Unify mouse pressed/released events across renderers

---

core/src/processing/opengl/PGL.java

Add missing 2D which disappeared in
https://github.com/processing/processing/pull/4052/files#diff-88c7dd4e8f37672d20e228a71a433a6dL1889
Fixes #4810

Fix typo in glsl preprocessor

---

core/src/processing/core/PShape.java

Fix #4826. I think the bug reporter is confused, since I can't reproduce the bug in P2D but I can in normal Java 2D. It's fixed in Java 2D now anyway.

Fix #4826. PShape in Java2D wasn't respecting kind.

---

java/src/processing/mode/java/Debugger.java
java/src/processing/mode/java/JavaEditor.java
java/src/processing/mode/java/JavaMode.java
java/src/processing/mode/java/runner/Runner.java

- Put stuff on correct threads and added proper synchronization
- Run button stays active after restarting sketch
- Run and Stop buttons now work reliably
- Restarting sketch with Run button while debugging is fixed

Improvements to sketch launching and stopping

---

core/src/processing/opengl/PSurfaceJOGL.java

Otherwise java.util.Timer used by FPSAnimator uses 10 or 15 ms resolution, which results in 60 fps sketches running at around 30 fps and 30 fps sketches running at around 21 fps.
Fixes #4846

Keep Windows timer resolution high for OpenGL sketches

---

app/src/processing/app/contrib/ContributionManager.java
app/src/processing/app/contrib/ListPanel.java
app/src/processing/app/contrib/UpdateListPanel.java

- Fire table change notifincations only after all changes happened
- In listeners, ignore contributions which are of different kind than current tab
- Remove redundant invokeLater() which spammed EDT with hundreds of Runnables
- Remove some manual sychronization since the code runs on EDT
- Remove two conditions which are always true
- Fix Update tab which broke in the process - contributions now stay on update screen with spinning wheel until installation completes

Grab bag of Contribution Manager fixes I accumulated while fixing other stuff

---

app/src/processing/app/Mode.java
app/src/processing/app/Sketch.java

It mostly worked, except
- old window did not get closed so you ended up with two sketchbook windows
- sketchbook was not being rebuilt when sketch was deleted
Also made sure old sketchbook window and old examples window are disposed before being rebuilt.
Fixes #2944

Rebuild sketchbook window when needed

---

core/src/processing/core/PSurfaceNone.java

When Java2D sketch crashes, closing the window does not stop Event
Dispatch Thread. This fix makes PApplet.exit() do the right thing and
not wait for surface to finish when the thread is already dead.
Fixes #4831

Allow JAVA2D to terminate when animation thread dies

---

java/src/processing/mode/java/JavaInputHandler.java

This PR replaces the keyChar check used to trigger auto-indent with a keyCode check, and fixes #4804. `Ctrl+J` happens to be an escape sequence representing new line (and their keyChar values are therefore both 10/`\n`), so `Ctrl+J` and `Ctrl+Shift+J` created a new line to appear when stepping. The keyCode for the Enter Key, however, is different, and hitting the Enter Key would be when the auto-format is triggered.

Replace keyChar with keyCode to prevent new line error when debugging

---

core/src/processing/core/PApplet.java
core/src/processing/core/ThinkDifferent.java
core/src/processing/opengl/PGraphicsOpenGL.java
core/src/processing/opengl/PSurfaceJOGL.java

These leaks don't matter--could never be noticed--in Java Mode, which just System.exit()s when the sketch is done. But the Python Mode sketch runner sticks around between invocations, which makes it susceptible to severe memory loss when, for example, many PShapes are created.
This patch does a few things.
Most noticeably, it refactors PGraphicsOpenGL's resource disposal technique to remove a ton of duplicated code. But it also throws away the "RefList" which not only didn't do a desirable thing, but kept resources from ever being released (since there was no way for resources to be removed from the RefList other than by their being disposed() which could only happen if they were released from the RefList!).
It also terminates an exception-catching thread at shutdown time (which otherwise …

Fix a number of memory leaks.

---

app/lib/jna.txt

The txt comment was out of date, so I changed the version number and pointed to maven folder/pom.
See this commit for reference: [56f742ee041966989324827b75f7e6f55ccf0da3](https://github.com/processing/processing/commit/56f742ee041966989324827b75f7e6f55ccf0da3)

Update jna.txt comment

---

build/shared/lib/languages/PDE.properties
build/shared/lib/languages/PDE_uk.properties
java/src/processing/mode/java/pdex/PDEX.java

A simple implementation for #4668 - adds a "Jump to Declaration" option to the PDEX context menu with the same functionality as ctrl-clicking on a variable (jumps to the declaration of the variable if it was declared within the sketch; otherwise shows its' usage instead).
In a Processing sketch, right-click on a variable, select "Jump to Declaration" and verify that the declaration is indeed being jumped to 😄

PDEX: Add 'Jump to Declaration' to right-click menu (#4668)

---

java/src/processing/mode/java/pdex/SourceUtils.java

Fix preprocessing of code with double backslash in string or char literal

---

core/src/processing/opengl/PGraphicsOpenGL.java

This caused register allocation issues before, but now this seem to be only still necessary for the binary GLES2 driver, where even enabling one more light (from 2 to 3) will make the shader compiler unhappy. Tested with 11.1.0-1+rpi1 on all P2D & P3D examples.

ARM: Allow Raspberry Pi's Mesa GL driver to use up to 8 lights

---

core/src/processing/opengl/PGL.java

No idea if tearing down the FBO half-way and setting it back up again is recommended practice, but this does make the `Primitives3D` example work for me with the Mesa VC4 driver (see #4919).

Retry with multisampling disabled if creating a framebuffer fails because of INCOMPLETE_MULTISAMPLE

---

core/src/processing/opengl/PGraphicsOpenGL.java

I must have a mistake setting up my testing environment - turn out we still need the custom shader hack for VC4, at least with Mesa 11.1.

Revert "ARM: Allow Raspberry Pi's Mesa GL driver to use up to 8 lights"

---

core/src/processing/core/PApplet.java

Some renderers (OpenGL) fire events on background threads, which can corrupt the event queue when the sketch is not looping and multiple threads add and remove from the queue at the same time.
This PR uses blocking queue to serialize enqueuing and lock to synchronize dequeuing.
In the ideal case, we should be able to invoke code on the animation thread (ala invokeLater) and always dequeue events from there even when the sketch is not looping.

Synchronize input event processing

---

core/src/processing/opengl/PSurfaceJOGL.java

This works around a JOGL bug that affects ARM Mali devices, such as the PocketCHIP. (reported by @xranby)

Unblock hardware-accelerated P3D on ARM Mali devices

---

java/src/processing/mode/java/preproc/PdePreprocessor.java

Scrub comments: skip the second chracter in the escape sequence

---

core/src/processing/core/PApplet.java

I was surprised that loading a 54 MB file with `loadBytes` took as long as it did (2.7 seconds). Hit the code with a hammer a little bit, and now it's down to 0.4 seconds. And seems to works for URLs still...

Improve loadBytes performance

---

core/src/processing/awt/PGraphicsJava2D.java

This fixes the bug for now, but uncovers a deeper issue.
PImage.modify flag is now used for two purposes and should be split into two variables:
- internally by renderers to signal that pixels[] changed and need to be drawn
- externally to signal other renderers that this image changed in some way and they should update their cache
When a PGraphics is drawn onto other PGraphics, both of these uses collide and may cause problems. This needs to be looked at and resolved later, probably by adding another variable (a flush counter which could be compared with couter of the cached image to tell if cache needs to be updated).
Reverts 51dff7689968c5da7344b61d53e90359eaf8329f
Fixes #5040

Revert updatePixels() to set modified flag to true

---

core/src/processing/core/PApplet.java

Java2D and FX2D send multiple PRESSED and only one RELEASE event (at
least on Windows). Therefore we have to keep track of what is pressed
and what not. Most keyboards do not support pressing more than ~10 keys
simultaneously, so this should not cause any performance problems.
See focusLost() for possible problem when user overrides it and does not call super. It's there only to clear keys when ALT+TAB is pressed so the chance somebody will hit this is low.
Fixes #5049

Fix keyPressed for multiple keys

---

app/src/processing/app/Console.java
app/src/processing/app/Language.java
app/src/processing/app/Preferences.java
app/src/processing/app/contrib/ContributionListing.java
app/src/processing/app/platform/LinuxPlatform.java
app/src/processing/app/ui/Recent.java

This is #5054 but also overwrites `getSettingsFolder` taking `$HOME` into account, so that `sudo -E` works. Since now the root user is now potentially writing into the settings folder, the patch tries to make those files world-writable.
Compared to #5054, this also handles these situations:
* more than one user running `sudo -E processing` (previously this created settings in the root users home directory pointing the sketch directory to the first that called)
* user having a custom path for the sketch folder set
* the root user having `.processing` & `sketchbook` herself (this is still possible to make use of by running `sudo` without the `-E`)
Modifying all files that get created by P5 to be world-writable is probably a futile attempt, but if this is the way to go I would consider …

Consider $SUDO_USER on Linux for locating the sketchbook folder

---

app/src/processing/app/Messages.java
app/src/processing/app/Sketch.java
app/src/processing/app/ui/ChangeDetector.java
build/shared/lib/languages/PDE.properties

Fixes #4713, fixes #4849. I've added a method to Messages that accepts custom buttons, and Messages.showYesNoQuestion is now based on it for Mac OS.

Make the change detector not reload the sketch

---

java/src/processing/mode/java/Compiler.java

Fixes #4878.
`long l = 121238081273;` gives "The type int can't handle numbers that big. Try 121238081273L to upgrade to long."
Anything else gives "Even the type *(e.g.)* long can't handle 8237418923078232103L. Research big numbers in Java."

Prompt the user to give the L suffix on numbers

---

build/build.xml
build/linux/appdata.xml
build/linux/desktop.template
build/linux/install.sh
build/linux/processing-processingide.xml
build/linux/uninstall.sh

Yo!
we had to celebrate that Carlos finished his thesis and decided to go in a hacking session ... and guess what ... we thought that it would be super-cool if the Processing IDE that we adore had a proper install script the same as the Arduino one.
We modified ant's build.xml file to add the files, as well as added the proper application files, install scripts, etc.
Using this patch, you will be able of installing the right icons in linux and let your users click directly on *.pde files for them to open automagically.
The last thing ... you should allow Processing to continue talking in 3rd person about itself ... it is such a nice IDE that we love and respect ...
Hugs from Sweden,
/Carlos and David
PS. you should revise the metadata for this to properly represent the Processing …

add install / uninstall scripts for linux a-la-Arduino + correct mime types for IDE

---

core/src/processing/opengl/PGraphicsOpenGL.java

Add defaultFontOrDeath to OpenGL textWidth.

---

java/src/processing/mode/java/runner/Runner.java

When runDisplay was set to -1 no display detection happened. Fixed it so that editor display is used.
Regression introduced in 6e9a8e0ceb5af0237885df2a860a64b0c5246a55
Fixes #5118

Fix "Could not parse -1 for --dsiplay" error

---

java/src/processing/mode/java/JavaBuild.java
java/src/processing/mode/java/pdex/PreprocessingService.java

In case somebody needs to work with native FX windows or events, here they are, ready to be imported (like AWT stuff).

Add JavaFX runtime to error checker class path

---

core/src/processing/awt/PSurfaceAWT.java
core/src/processing/core/PApplet.java

The detailed issue can be found here -> https://github.com/processing/processing/issues/5052. A fix for that is applied by checking if the height being set is zero and if so, resetting it to 1(to make it greater than zero).

A fix for the window resizing problem in Windows

---

core/src/processing/core/PApplet.java

Recent OS X releases no longer come with the "Pipe Organ" voice installed by default. As a result, the exec example fails silently with no console feedback. Removing the -v voice argument causes the example to work on current OS X -- and still work on older OS X.

Remove "Pipe Organ" from exec javadoc

---

java/libraries/net/src/processing/net/Client.java
java/libraries/net/src/processing/net/Server.java

Fixes
- Fix synchronization (probably fixes #4419)
- Compact client buffer before making it bigger (fixes #5360)
- Set limit to the size of client buffer (128 MB - might be too much)
Performance, style
- Read blocks of data instead of byte by byte
- Remove sleep in the server loop (probably there to 'fix' some threading issues)
- Code cleanup (creating varargs arrays manually, missing Override annotations)
Features
- Server now calls `clientEvent(Client c)` if it receives data from any client (fixes #3970)
- Unwrap exceptions thrown from the user code before printing them to the console

Fixes for Net library

---

core/src/processing/core/PApplet.java

This fixes the first error mentioned in the issue, but not the other one mentioned by @christianbender. Tested on OSX High Sierra (10.13.2)

fix NPE when closing sketch window on Mac (#5214)

---

core/src/processing/core/PApplet.java

when file is not found, a null pointer exception crashes processing i guess is because these lines.

make "loadXML(String)" handle "file not found"

---

core/src/processing/opengl/PGL.java
core/src/processing/opengl/PJOGL.java

This makes P3D work on Linux SBCs using ARM Mali graphics and their (closed-source) OpenGL ES 3.1 driver.
I don't have matching hardware, so all testing was done by user seongwook in the Processing Forums, who was very generous with his time in this effort. He tested with an ODROID-XU4 board, which reports a "Mali-T628" model and the following driver string "OpenGL ES 3.1 v1.r17p0-01rel0.a881d28363cdb20f0017ed13c980967e".
Re review: I specifically don't know if my code in d351070d30afe4861e04ec04c55af4a69770570f makes sense in this way.

ARM Mali upbringing

---

core/src/processing/data/XML.java

I have included the `@nowebref` and `@brief` tags like similar functions have, not sure if this was the right move, just mimicing what other javadocs had.
Of course the `@nowebref` has an explanation: there is no web reference for trim(), but I wasn't sure about the `@brief`.

added javadoc comment for XML#trim()

---

core/src/processing/opengl/PGraphicsOpenGL.java

@codeanticode @JakubValtar This patch should not be controversial really, but in doing so I came across something that looked a bit strange to me: if you search the tree for `POLYGON_SMOOTH`, you'll find a hit in `restoreGL` and one in `setGLSettings` - but one of them is done unconditionally, and one just when `1 <= smooth` ... bug?

ARM Mali: Don't use GL_MULTISAMPLE or GL_POLYGON_SMOOTH on ES

---

core/src/processing/opengl/PJOGL.java

@benfry: Another fallout from 3.3.7.1

OpenGL ES: Fix GLSL version number for 1.00 (#5582)

---

app/src/processing/app/Sketch.java
app/src/processing/app/ui/ChangeDetector.java

Fixes #5466
Update was done by switching to the next tab and then back to the prev tab, however that is a no-op in a single tab sketch. Updated the code to reload the current code if it was modified.

Make sure editor is updated after reloading changes

---

core/src/processing/core/PShape.java

Currently, PShape.contains() throws a fatal exception when called on a non-PATH PShape object. This change allows the method to be called also on GROUP objects; in this case, it will loop through children and call `.contains()` on all of them until a match is found. Unsupported children (i.e. non-PATH or non-GROUP objects) will be skipped gracefully and a warning will be generated, but no fatal error will be emitted.

Support PShape.contains() on GROUP objects

---

core/src/processing/core/PApplet.java

This PR modifies the javaPlatform extraction method so it works with the newest java.version format (as per JEP-223).

Fixed for JEP-223 support

---

core/src/processing/core/PGraphics.java

Blend mode can incorrectly be set to REPLACE in P2D when rendering certain bitmap fonts. This breaks rendering of images with alpha channels in the same sketch on 3.4. See #5645 which is fixed by this PR.

Fixes blend mode not being set correctly, fixing #5645.

---

core/src/processing/awt/PSurfaceAWT.java
core/src/processing/core/PApplet.java
core/src/processing/javafx/PSurfaceFX.java
core/src/processing/opengl/PSurfaceJOGL.java

Make sure PRESS, DRAG and RELEASE report the same mouse button on MacOS.
- If CTRL was pressed during Left PRESS, report Right Button until the button is released, regardless of whether CTRL is still down.
- If CTRL was not pressed during Left PRESS, report Left Button until the button is released, regardless of CTRL state.
Fixes #5672

Make sure Ctrl+Left Mouse on MacOS is consistent

---

core/src/processing/core/PApplet.java

Frame rate counter finally gets its ticket for speeding.
Frame rate is now calculated by averaging frame times instead of averaging frame rates. Rationale is explained in the comment.

Stop frame rate counter from exaggerating

---

core/src/processing/opengl/PGraphicsOpenGL.java

Poly vertex buffer was initialized with 3 components, but has 4.

Fix vertex buffer initialized with wrong number of components

---

core/src/processing/opengl/PGraphicsOpenGL.java

Otherwise FBOs keep the old size and things understandably break.

Recreate FBOs when offscreen PGraphicsOpenGL is resized

---

app/src/processing/app/ui/Editor.java
app/src/processing/app/ui/EditorStatus.java

Fixes #970. Gives a bit more room to code on a smaller screen. I haven't automatically unhidden it when the sketch starts since that's just bothering the user and the status bar still changes colour on exceptions. Also, I'm not leaving space for the `RIGHT_MARGIN` in EditorStatus; should I be? (N.B. you have push access to my PR branches, feel free to make trivial changes to constants/text etc. rather than describing them to me when that's convenient).
Also (mouseExited listener) fixed a bug where if you moved your mouse off an URL in the status bar vertically it would stay the hovered-over color because it only cares about `mouseX`.

Add console hiding button

---

core/src/processing/core/PShape.java
core/src/processing/core/PShapeSVG.java

Hello Processing maintainers !
I work on a side project called [Soby](https://github.com/poqudrof/Soby) in which I do slideshows based on SVGs, it is based on an older [Sozi](https://github.com/senshu/Sozi). 
I extended a little bit the support of SVGs and now with Java 8 and stuff like the Base64 decoder I have a rather clean solution. 
- Support of embedded images in SVGs, linked images are supported but should not be avoided if possible.
- Text and image locations are identical to SVG visualized in Inkscape. 
When the font works, it fits perfectly. 
- Low modification of current code except for new parsing functions. 
- I introduce some code duplication in :
``` java
private void loadBase64Image() 
```
- I have no idea how to handle text quality in a clean way... :
``` java
public …
```

Extended support of SVG format

---

core/src/processing/core/PFont.java

I fixed this 'issue' (enchantment) #5481. createFont(...) shows a warning when a named font (without extension) is not found on the system.
**Code**
`void setup() {
PFont font = createFont("unknown",20);
}`
**Output**
`Warning: font "unknown" is missing or inaccessible on this system. Default font "Dialog.plain" is used.`

Shows a warning when createFont can't find a named font (#5481)

---

core/src/processing/core/PApplet.java

When a control-click occurs, the macosxLeftButtonWithCtrlPressed flag
was set, but was never being unset due to accidental comparison with
the button variable instead of action variable. All future mouse
operations reported as right-click on Mac OS. This fixes the comparison
so that only the operations from a mouse press with the control button
down are reported as RIGHT. The flag is cleared after mouse release.

Fix bug with control-click for RIGHT on Mac OS, addresses #5765

---

build/shared/lib/languages/PDE_uk.properties

Updates my 2016 Ukrainian translation file to add in some of the newer localization strings.
The various `keystroke` strings are copied to this file, despite being identical to the originals. Let me know if these should be removed outright!

Add new strings to Ukrainian translation

---

core/src/processing/core/PFont.java

When 'detail' is set to 0, it was causing getShape to break with OTF fonts that use cubic bezier paths.
By mistake, a 3D quadratic was being drawn instead of a proper cubic bezier.

getShape() - Type of vertex was wrong for Cubic

---

.github/workflows/lock.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening
